spring:
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT_BASE}
        chat:
          options:
            deployment-name: ${DEPLOYMENT_NAME}
