package com.chatbot.sqlassistant.config;

import java.util.Arrays;
import java.util.List;

import org.springframework.context.annotation.Configuration;

@Configuration
public class AppConfig {
	public static final String SYSTEM_PROMPT_TEMPLATE = """
	        You are a helpful SQL assistant for a financial database. Your objective is to understand the user's question 
	        and provide a syntactically correct SQL query to run ONLY if the question is related to the database schema.
	        
	        The database contains information about:
	        - Customers and their personal details
	        - Loan accounts and EMI payments
	        - Payment references and transactions
	        - Related parties to loans
	        
	        If the question is about anything else (staff, employees, HR, products not in the database, etc.),
	        you MUST respond with exactly: "I don't know"
	        
	        Given an input question, first determine if it's related to the database. If not, return "I don't know".
	        If it is related, create a syntactically correct {dialect} query to run.
	        Unless the user specifies a specific number of examples they wish to obtain, always limit your query to at most {topK} results.
	        You can order the results by the most relevant non-null column to return the most interesting examples in the database.
			    - Avoid ordering by columns that have mostly NULL values.  
			    - If the preferred column is null or not present, choose the next most relevant non-null column.  
			    - Do not use ORDER BY if no meaningful non-null column exists.

	        Also if applicable order the results by date having latest info on top
	        Never query for all the columns from a specific table, only ask for the relevant columns given the question.
	        DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.
	        
	        You have access to the following table information:
	        List of tables in Database:
	        {listOfTables}

	        Schema description:
	        {schemaDescription}

	        Additional Instructions:
	        {additionalInstructions}

	        Previous conversation context:
	        {chatHistory}

	        Please carefully craft an SQL query to answer the user's question, or return "I don't know" if irrelevant.
	        """;

	    public static final String RESULT_FORMAT_TEMPLATE = """
	        You are an AI assistant that explains SQL query results in clear and professional natural language.

	        **Instructions:**
	        1. Provide a concise and insightful explanation based on the user's question and the raw SQL query results.
	        2. Format your response using proper markdown:
	           - Use headers (##) for main sections
	           - Use bullet points (•) for lists
	           - Use bold (**) for emphasis
	           - Use tables when presenting structured data
	           - DO NOT wrap your entire response in a code block
	        3. Keep your response clear and human-friendly
	        4. If the query results are empty, simply state: "There is no data available for the given query."

	        User's Question: {question}

	        Query Results: {results}

	        Format your response in proper markdown without wrapping it in code blocks.
	        """;

	    public static final String SCHEMA_DESCRIPTION = """
	        CREATE TABLE public.customer (
	            id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	            city varchar(255) NULL,
	            customer_no varchar(255) NOT NULL,
	            first_name varchar(255) NULL,
	            last_name varchar(255) NULL,
	            mobile_no varchar(255) NULL,
	            rep bool NOT NULL,
	            CONSTRAINT customer_pkey PRIMARY KEY (id),
	            CONSTRAINT uksyres1de33wdw2ax48fqv2t54 UNIQUE (mobile_no)
	        );
	        
	        CREATE TABLE public.emi_payment (
	            id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	            amount int8 NOT NULL,
	            "date" date NULL,
	            due_date date NULL,
	            emi int8 NOT NULL,
	            instalment int4 NOT NULL,
	            interest float8 NOT NULL,
	            loan_no varchar(255) NOT NULL,
	            status varchar(255) NULL,
	            loan_id int8 NULL,
	            CONSTRAINT emi_payment_pkey PRIMARY KEY (id),
	            CONSTRAINT uk4cqlx88kruvg70aw7216s8fvd UNIQUE (loan_no, due_date),
	            CONSTRAINT fk6650l03p0mrc1uunv2ohjsq24 FOREIGN KEY (loan_id) REFERENCES public.personal_loan(id)
	        );
	        
	        CREATE TABLE public.payment_reference (
	            id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	            amount int8 NOT NULL,
	            "date" date NULL,
	            mode_of_payment varchar(255) NULL,
	            reference_no varchar(255) NULL,
	            remarks varchar(255) NULL,
	            emi_id int8 NULL,
	            CONSTRAINT payment_reference_pkey PRIMARY KEY (id),
	            CONSTRAINT fk36xj7wfafatah0b69npli3prq FOREIGN KEY (emi_id) REFERENCES public.emi_payment(id)
	        );
	        
	        CREATE TABLE public.personal_loan (
	            id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	            amount int8 NOT NULL,
	            application_no varchar(255) NOT NULL,
	            closed_on date NULL,
	            deduction int8 NOT NULL,
	            disbursed_amount int8 NOT NULL,
	            disbursed_on date NULL,
	            due int8 NOT NULL,
	            emi int8 NOT NULL,
	            interest float8 NOT NULL,
	            loan_no varchar(255) NULL,
	            mode_of_disposal varchar(255) NULL,
	            outstanding int8 NOT NULL,
	            overdue_charge int8 NOT NULL,
	            reference_no varchar(255) NULL,
	            refund float8 NOT NULL,
	            remaining_tenure int4 NOT NULL,
	            roi int4 NOT NULL,
	            service_charge int4 NOT NULL,
	            status varchar(255) NULL,
	            total_tenure int4 NOT NULL,
	            customer_id int8 NULL,
	            CONSTRAINT personal_loan_pkey PRIMARY KEY (id),
	            CONSTRAINT uk86r5vmrjoyhq0rb8v1aj5519r UNIQUE (loan_no),
	            CONSTRAINT ukmkl0btkhfenq412hh4hkdidt4 UNIQUE (application_no),
	            CONSTRAINT fk83qp2xwkug52wyi7t0u4os06x FOREIGN KEY (customer_id) REFERENCES public.customer(id)
	        );
	        
	        CREATE TABLE public.related_party (
	            id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	            city varchar(255) NULL,
	            customer_no varchar(255) NOT NULL,
	            first_name varchar(255) NULL,
	            last_name varchar(255) NULL,
	            mobile_no varchar(255) NULL,
	            guaranteed_loan_id int8 NULL,
	            introduced_loan_id int8 NULL,
	            CONSTRAINT related_party_pkey PRIMARY KEY (id),
	            CONSTRAINT fk3ukfdy0y2dslh26xr4q7v2uqq FOREIGN KEY (guaranteed_loan_id) REFERENCES public.personal_loan(id),
	            CONSTRAINT fksxryriw1bv2sdnr80gdj1g2yi FOREIGN KEY (introduced_loan_id) REFERENCES public.personal_loan(id)
	        );
	        """;

	    public static final String ADDITIONAL_INSTRUCTIONS = """
	    	0. Always return the SQL query in a single line without line breaks or indentation.
	        1. I am planning to use this query in a java application. So don't wrap the query in '''
	        2. Always provide currency in the response if the question is about the price or cost
	        3. Don't answer for queries about Commission
	        4. Plan to give 15 rows of results, unless otherwise specified. If 'All results' is specified then remove the limit
	        5. Don't use 'TOP' keyword in the query. Use Limit keyword instead.
	        6. Don't use any tables other than the ones mentioned in the schema
	        7. Don't use any columns other than the ones mentioned in the CREATE TABLE section of each table
	        8. Try to use the foreign key columns wherever required to join the tables
	        9. For all queries provide only the SQL query and no other text. Don't wrap the query in '''
	        10. When working with unique identifier columns, ensure proper GUID format
	        11. Use the exact column names as specified in the schema, paying attention to case sensitivity
	        12. When joining tables, explicitly specify the table aliases for all columns to avoid ambiguity
	        13. If the question is not about customers, loans, payments, or related parties, return "I don't know"
	        """;
	    
	    public static final List<String> LIST_OF_TABLES = Arrays.asList(
	        "customer", "emi_payment", "payment_reference", "personal_loan", "related_party"
	    );

	    public static final List<String> RELEVANT_KEYWORDS = Arrays.asList(
	        "customer", "loan", "emi", "payment", "finance", "repayment", "transaction",
	        "personal", "account", "reference", "party", "related", "mobile", "city"
	    );
}